### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by rhodgkins** [feedhenry/fh-ios-sdk#41]
Hi,

Would you mind if I added [Carthage](https://github.com/Carthage/Carthage) support to the Feedhenry iOS SDK?

Cheers,

Rich

**Comment by wei-lee** [comment]
@rhodgkins no, not at all. Feel free to add support for that.

**Comment by rhodgkins** [comment]
@wei-lee great thanks! Been looking into it and [got it working](https://github.com/rhodgkins/fh-ios-sdk/tree/carthage) but as you don't have Pods checked in the dependencies are missing when carthage pulls and builds. Is there a reason they're not checked in? :)

**Comment by wei-lee** [comment]
@rhodgkins I think we have the Pods dir checked into the repo at some point, but we didn't find it's useful and it significantly increases the size of the repo, and sometimes makes it difficult to see actual code changes when there are dependency updates. So we removed it from the repo.

Can you just run
```
pod install
```
to install the dependencies first?

**Comment by rhodgkins** [comment]
Unfortuantely carthage doesn't give you that "hook" before compiling the library. I think I can get around it by have the framework target have dependencies based on carthage created frameworks instead and just have those single `.framework` files in. I shall have a play around :)

**Comment by Nathan187** [comment]
any update on this.  is there carthage support?

**Comment by danielpassos** [comment]
Hey @rhodgkins, @Nathan187 

Just a heads up on this, I have create a taks for it. We are going to work on this one after finish all we need to support iOS 11

Keep in touch in https://issues.jboss.org/browse/FH-4316
