### ISSUE TITLE
Proposal: Extract sync implementation to separate project

### ISSUE THREAD

**Issue by wtrocki** [feedhenry/fh-ios-sdk#95]
## Proposal

Rewrite and extract sync implementation into separate library. 
Port ObjectiveC code to swift.
Integrate new library into fh-ios-sdk 

## Justification

Allow to use sync library without sdk
Swift based implementation will help to gain more traction with community

## Things to consider

Storage. Using core data, database etc.
Background sync (research patterns on IOS platform)
Possibility to use different storage solution for better performance.

Extraction should include:
- Ability to provide external networking library if needed
- Ability to generate different clients
- Default network handler
- Default client id generator

I'm researching this at the moment to provide more information for this proposal.

**Comment by wtrocki** [comment]
FYI @danielpassos @aidenkeating @wei-lee 

I'm researching this area at the moment. 
Going to update this proposal with more details and send it to aerogear community list for acceptance. Happy to incorporate any suggestions etc.

**Comment by wei-lee** [comment]
@wtrocki Thanks for the proposal. I think it's a good idea to extract sync out to its own (but not sure if it's own repo, or just a different sub folder). But there are a lot of stuff in your proposal here, and I think it will be hard to achieve all this in a single attempt.

So perhaps maybe let's take one step a time - the goal of the first step is to just make sure sync can work on its own, use the existing implementation as much as possible. 

Once we have that, we can then decide what to do next - I believe most of the points you listed here are valid, but I think most of them require proposals on its own.

WDYT?

**Comment by wtrocki** [comment]
Great idea! I extracted existing code and were focusing on refactoring/changing things to swift, but actually we can do that in phases. I will change proposal to focus on this aspect only.

**Comment by wtrocki** [comment]
Going to move this issue to aerogear proposals area for visibility. 
Closing for now.
